
name: 'Terraform'

on:
  push:
    branches: [ "harness_tf" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Init, Format, and Plan'
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}             
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}     
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} 
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan
    
    # Upload the Terraform plan file as an artifact for use in the "Terraform Apply" job
    # - name: Upload Terraform Plan
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: tfplan-artifacts
    #     path: |
    #         tfplan
    #         .terraform.lock.hcl
    #         .terraform/

  apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}             
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}     
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} 
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    needs: terraform
    environment:
      name: development
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    # # Download the Terraform plan file artifact that was uploaded in the "Terraform Plan" job
    # - name: Download Terraform Plan
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: tfplan-artifacts

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/harness_tf' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan
